/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_TAP_DANCE_ENTRIES 4
#define VIAL_COMBO_ENTRIES 4

#define VIAL_KEYBOARD_UID {0xED, 0xB5, 0x12, 0x45, 0xED, 0x07, 0xCD, 0xAE}

#undef RGBLIGHT_ANIMATIONS
#define RGBLIGHT_EFFECT_BREATHING
// #define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
